### PR TITLE
fix electricalSeries default inputs

### LINKED ISSUE #53: Why is `electrodesTablePath` needed?
https://github.com/NeurodataWithoutBorders/aqnwb/blob/00aa1caff04ce9938b4d07c937859cdc34004539/src/nwb/ecephys/ElectricalSeries.cpp#L12

is required when creating an `ElectricalSeries`. It is unclear to me why is this is needed? The NWB schema specifies a single `ElectrodesTable` that is in a fixed location in the file. As such, the `electrodesTablePath` should be the same for all NWB files.

### LINKED ISSUE #54: `ElectricalSeries.units` should not be setable
https://github.com/NeurodataWithoutBorders/aqnwb/blob/00aa1caff04ce9938b4d07c937859cdc34004539/src/nwb/ecephys/ElectricalSeries.hpp#L30

provides a default value of `volts` but allows the user to change the untis. However, in the `NWBSchema` the value for `units` are fixed to `volts`, and as such no other value is allowed. We should, hence, not allow the user to set this value but fix it to `volts` in the code.

### LINKED ISSUE #55: Invalid default values for `ElectricalSeries.dsetSize` and `ElectricalSeries.chunkSize`
https://github.com/NeurodataWithoutBorders/aqnwb/blob/00aa1caff04ce9938b4d07c937859cdc34004539/src/nwb/ecephys/ElectricalSeries.hpp#L32-L33

specify vectors with a single element as the default parameter. However, the `ElectricalSeries` data must always be 2D and the second dimension must have the same length as the number of electrods/channels. As such, the default values are not valid, potentially resulting in the creation of an invalid file. I think we can simply remove the default values and require that they must be specified.

### PR DESCRIPTION
**Pull request by stephprince**
Fix several issues related to the inputs to `ElectricalSeries` in preparation for new data types that will inherit from ElectricalSeries.
* fix #53 
* fix #54 
* fix #55

Regarding #53, I didn't realize the path was specified in the schema and there is only a single `ElectrodesTable` - that makes things easier!

### CODE REVIEW

File: src/nwb/ecephys/ElectricalSeries.hpp [hunk 1]
```diff
@@ -81,7 +77,7 @@ class ElectricalSeries : public TimeSeries
   /**
    * @brief Path to the electrodes table this time series references
    */
-  std::string electrodesTablePath;
+  std::string electrodesTablePath = "/general/extracellular_ephys/electrodes/";
```
Comment (oruebel) [inline src/nwb/ecephys/ElectricalSeries.hpp:80]:
```suggestion
  inline static const std::string electrodesTablePath = "/general/extracellular_ephys/electrodes/";
```

Comment (oruebel) [reply src/nwb/ecephys/ElectricalSeries.hpp:80]: Actually, I would make `electrodeTablePath` a `static const` member of `ElectrodeTable` such that we can just grab from the `ElectrodeTable` class, rather than making it a property of `ElectricalSeries`. Alternatively, it could also be a `static const` member of `NWBFile` since it really defines where the `ElectrodesTable` goes.

File: tests/testFile.cpp [hunk 2]
```diff
@@ -11,7 +11,7 @@ using namespace AQNWB;
 
 TEST_CASE("ElectrodeTable", "[ecephys]")
 {
-  std::string path = "/electrodes/";
+  std::string path = "/general/extracellular_ephys/electrodes/";
```
Comment (oruebel) [inline tests/testFile.cpp:14]: If we make the `electrodeTablePath` a `const static` property then we can also avoid duplicating it here and the other places this path is defined, because it is then fixed at compile time.

**Review by oruebel — COMMENTED** [review]
Other than the minor comment about moving `electrodeTablePath` and making it `const` this looks good.

File: src/nwb/ecephys/ElectricalSeries.hpp (hunk 1 above)
Comment (stephprince) [reply src/nwb/ecephys/ElectricalSeries.hpp]: I see, yes that looks better and minimizes the path duplication. I implemented on `ElectrodeTable`

**Review by oruebel — APPROVED** [review]
Looks good to me
